[build]
  base = "website"
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/adb/*"
  to = "/.netlify/functions/adb/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0, s-maxage=0"
    Pragma = "no-cache"
    Expires = "0"
    CDN-Cache-Control = "no-store"
    Cloudflare-CDN-Cache-Control = "no-store"
